template: testify
force-file-write: true

packages:
  github.com/daniildddd/maestro/internal/features/auth/transport:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mocks_test.go"
      pkgname: "transport_test"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      AuthService:

  github.com/daniildddd/maestro/internal/features/auth/service:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mocks_test.go"
      pkgname: "service_test"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      AuthRepository:
      PasswordHasher:
      AccessTokenGenerator:
      RefreshTokenManager:

  github.com/daniildddd/maestro/internal/features/users/transport:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mocks_test.go"
      pkgname: "transport_test"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      UsersService:

  github.com/daniildddd/maestro/internal/features/users/service:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mocks_test.go"
      pkgname: "service_test"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      UsersRepository:
      PasswordHasher:

  github.com/daniildddd/maestro/internal/core/repository/postgres:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mocks_test.go"
      pkgname: "postgres_test"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      Pool:
        configs:
          - dir: internal/features/auth/repository
            pkgname: repository_test
          - dir: internal/features/users/repository
            pkgname: repository_test
      Row:
        configs:
          - dir: internal/features/auth/repository
            pkgname: repository_test
          - dir: internal/features/users/repository
            pkgname: repository_test
      Rows:
        config:
          dir: internal/features/users/repository
          pkgname: repository_test