// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"context"
	"time"

	"github.com/daniildddd/maestro/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordHasher creates a new instance of MockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordHasher {
	mock := &MockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type MockPasswordHasher struct {
	mock.Mock
}

type MockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordHasher) EXPECT() *MockPasswordHasher_Expecter {
	return &MockPasswordHasher_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) Verify(hash string, plain string) error {
	ret := _mock.Called(hash, plain)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hash, plain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordHasher_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPasswordHasher_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - hash
//   - plain
func (_e *MockPasswordHasher_Expecter) Verify(hash interface{}, plain interface{}) *MockPasswordHasher_Verify_Call {
	return &MockPasswordHasher_Verify_Call{Call: _e.mock.On("Verify", hash, plain)}
}

func (_c *MockPasswordHasher_Verify_Call) Run(run func(hash string, plain string)) *MockPasswordHasher_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordHasher_Verify_Call) Return(err error) *MockPasswordHasher_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordHasher_Verify_Call) RunAndReturn(run func(hash string, plain string) error) *MockPasswordHasher_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccessTokenGenerator creates a new instance of MockAccessTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessTokenGenerator {
	mock := &MockAccessTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccessTokenGenerator is an autogenerated mock type for the AccessTokenGenerator type
type MockAccessTokenGenerator struct {
	mock.Mock
}

type MockAccessTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessTokenGenerator) EXPECT() *MockAccessTokenGenerator_Expecter {
	return &MockAccessTokenGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockAccessTokenGenerator
func (_mock *MockAccessTokenGenerator) Generate(userID uuid.UUID, role string) (string, error) {
	ret := _mock.Called(userID, role)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string) (string, error)); ok {
		return returnFunc(userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string) string); ok {
		r0 = returnFunc(userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = returnFunc(userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccessTokenGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockAccessTokenGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID
//   - role
func (_e *MockAccessTokenGenerator_Expecter) Generate(userID interface{}, role interface{}) *MockAccessTokenGenerator_Generate_Call {
	return &MockAccessTokenGenerator_Generate_Call{Call: _e.mock.On("Generate", userID, role)}
}

func (_c *MockAccessTokenGenerator_Generate_Call) Run(run func(userID uuid.UUID, role string)) *MockAccessTokenGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *MockAccessTokenGenerator_Generate_Call) Return(s string, err error) *MockAccessTokenGenerator_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAccessTokenGenerator_Generate_Call) RunAndReturn(run func(userID uuid.UUID, role string) (string, error)) *MockAccessTokenGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenManager creates a new instance of MockRefreshTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenManager {
	mock := &MockRefreshTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenManager is an autogenerated mock type for the RefreshTokenManager type
type MockRefreshTokenManager struct {
	mock.Mock
}

type MockRefreshTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenManager) EXPECT() *MockRefreshTokenManager_Expecter {
	return &MockRefreshTokenManager_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockRefreshTokenManager
func (_mock *MockRefreshTokenManager) Generate() (string, time.Time, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, time.Time, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() time.Time); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRefreshTokenManager_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockRefreshTokenManager_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockRefreshTokenManager_Expecter) Generate() *MockRefreshTokenManager_Generate_Call {
	return &MockRefreshTokenManager_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockRefreshTokenManager_Generate_Call) Run(run func()) *MockRefreshTokenManager_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRefreshTokenManager_Generate_Call) Return(token string, expiresAt time.Time, err error) *MockRefreshTokenManager_Generate_Call {
	_c.Call.Return(token, expiresAt, err)
	return _c
}

func (_c *MockRefreshTokenManager_Generate_Call) RunAndReturn(run func() (string, time.Time, error)) *MockRefreshTokenManager_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockRefreshTokenManager
func (_mock *MockRefreshTokenManager) Hash(rawToken string) string {
	ret := _mock.Called(rawToken)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(rawToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRefreshTokenManager_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockRefreshTokenManager_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - rawToken
func (_e *MockRefreshTokenManager_Expecter) Hash(rawToken interface{}) *MockRefreshTokenManager_Hash_Call {
	return &MockRefreshTokenManager_Hash_Call{Call: _e.mock.On("Hash", rawToken)}
}

func (_c *MockRefreshTokenManager_Hash_Call) Run(run func(rawToken string)) *MockRefreshTokenManager_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRefreshTokenManager_Hash_Call) Return(s string) *MockRefreshTokenManager_Hash_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRefreshTokenManager_Hash_Call) RunAndReturn(run func(rawToken string) string) *MockRefreshTokenManager_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// DeleteRefreshToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) DeleteRefreshToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockAuthRepository_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockAuthRepository_Expecter) DeleteRefreshToken(ctx interface{}, token interface{}) *MockAuthRepository_DeleteRefreshToken_Call {
	return &MockAuthRepository_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, token)}
}

func (_c *MockAuthRepository_DeleteRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthRepository_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_DeleteRefreshToken_Call) Return(err error) *MockAuthRepository_DeleteRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockAuthRepository_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenByHash provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetRefreshTokenByHash(ctx context.Context, token string) (domain.RefreshToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenByHash")
	}

	var r0 domain.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.RefreshToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.RefreshToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(domain.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetRefreshTokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenByHash'
type MockAuthRepository_GetRefreshTokenByHash_Call struct {
	*mock.Call
}

// GetRefreshTokenByHash is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockAuthRepository_Expecter) GetRefreshTokenByHash(ctx interface{}, token interface{}) *MockAuthRepository_GetRefreshTokenByHash_Call {
	return &MockAuthRepository_GetRefreshTokenByHash_Call{Call: _e.mock.On("GetRefreshTokenByHash", ctx, token)}
}

func (_c *MockAuthRepository_GetRefreshTokenByHash_Call) Run(run func(ctx context.Context, token string)) *MockAuthRepository_GetRefreshTokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_GetRefreshTokenByHash_Call) Return(refreshToken domain.RefreshToken, err error) *MockAuthRepository_GetRefreshTokenByHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockAuthRepository_GetRefreshTokenByHash_Call) RunAndReturn(run func(ctx context.Context, token string) (domain.RefreshToken, error)) *MockAuthRepository_GetRefreshTokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetUserByID(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockAuthRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockAuthRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockAuthRepository_GetUserByID_Call {
	return &MockAuthRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockAuthRepository_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthRepository_GetUserByID_Call) Return(user domain.User, err error) *MockAuthRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockAuthRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByName provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetUserByName(ctx context.Context, username string) (domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByName")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetUserByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByName'
type MockAuthRepository_GetUserByName_Call struct {
	*mock.Call
}

// GetUserByName is a helper method to define mock.On call
//   - ctx
//   - username
func (_e *MockAuthRepository_Expecter) GetUserByName(ctx interface{}, username interface{}) *MockAuthRepository_GetUserByName_Call {
	return &MockAuthRepository_GetUserByName_Call{Call: _e.mock.On("GetUserByName", ctx, username)}
}

func (_c *MockAuthRepository_GetUserByName_Call) Run(run func(ctx context.Context, username string)) *MockAuthRepository_GetUserByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_GetUserByName_Call) Return(user domain.User, err error) *MockAuthRepository_GetUserByName_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepository_GetUserByName_Call) RunAndReturn(run func(ctx context.Context, username string) (domain.User, error)) *MockAuthRepository_GetUserByName_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) SaveRefreshToken(ctx context.Context, token domain.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_SaveRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshToken'
type MockAuthRepository_SaveRefreshToken_Call struct {
	*mock.Call
}

// SaveRefreshToken is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockAuthRepository_Expecter) SaveRefreshToken(ctx interface{}, token interface{}) *MockAuthRepository_SaveRefreshToken_Call {
	return &MockAuthRepository_SaveRefreshToken_Call{Call: _e.mock.On("SaveRefreshToken", ctx, token)}
}

func (_c *MockAuthRepository_SaveRefreshToken_Call) Run(run func(ctx context.Context, token domain.RefreshToken)) *MockAuthRepository_SaveRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RefreshToken))
	})
	return _c
}

func (_c *MockAuthRepository_SaveRefreshToken_Call) Return(err error) *MockAuthRepository_SaveRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_SaveRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token domain.RefreshToken) error) *MockAuthRepository_SaveRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
