// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transport_test

import (
	"context"

	"github.com/daniildddd/maestro/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectorsService creates a new instance of MockConnectorsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectorsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectorsService {
	mock := &MockConnectorsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectorsService is an autogenerated mock type for the ConnectorsService type
type MockConnectorsService struct {
	mock.Mock
}

type MockConnectorsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectorsService) EXPECT() *MockConnectorsService_Expecter {
	return &MockConnectorsService_Expecter{mock: &_m.Mock}
}

// CreateConnector provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) CreateConnector(ctx context.Context, name string, config map[string]string) (domain.Connector, error) {
	ret := _mock.Called(ctx, name, config)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnector")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) (domain.Connector, error)); ok {
		return returnFunc(ctx, name, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) domain.Connector); ok {
		r0 = returnFunc(ctx, name, config)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = returnFunc(ctx, name, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_CreateConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConnector'
type MockConnectorsService_CreateConnector_Call struct {
	*mock.Call
}

// CreateConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - config map[string]string
func (_e *MockConnectorsService_Expecter) CreateConnector(ctx any, name any, config any) *MockConnectorsService_CreateConnector_Call {
	return &MockConnectorsService_CreateConnector_Call{Call: _e.mock.On("CreateConnector", ctx, name, config)}
}

func (_c *MockConnectorsService_CreateConnector_Call) Run(run func(ctx context.Context, name string, config map[string]string)) *MockConnectorsService_CreateConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectorsService_CreateConnector_Call) Return(connector domain.Connector, err error) *MockConnectorsService_CreateConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockConnectorsService_CreateConnector_Call) RunAndReturn(run func(ctx context.Context, name string, config map[string]string) (domain.Connector, error)) *MockConnectorsService_CreateConnector_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectorsService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockConnectorsService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockConnectorsService_Expecter) Delete(ctx any, name any) *MockConnectorsService_Delete_Call {
	return &MockConnectorsService_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockConnectorsService_Delete_Call) Run(run func(ctx context.Context, name string)) *MockConnectorsService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectorsService_Delete_Call) Return(err error) *MockConnectorsService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectorsService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockConnectorsService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectorByID provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) GetConnectorByID(ctx context.Context, name string) (domain.Connector, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectorByID")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Connector, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Connector); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_GetConnectorByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectorByID'
type MockConnectorsService_GetConnectorByID_Call struct {
	*mock.Call
}

// GetConnectorByID is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockConnectorsService_Expecter) GetConnectorByID(ctx any, name any) *MockConnectorsService_GetConnectorByID_Call {
	return &MockConnectorsService_GetConnectorByID_Call{Call: _e.mock.On("GetConnectorByID", ctx, name)}
}

func (_c *MockConnectorsService_GetConnectorByID_Call) Run(run func(ctx context.Context, name string)) *MockConnectorsService_GetConnectorByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectorsService_GetConnectorByID_Call) Return(connector domain.Connector, err error) *MockConnectorsService_GetConnectorByID_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockConnectorsService_GetConnectorByID_Call) RunAndReturn(run func(ctx context.Context, name string) (domain.Connector, error)) *MockConnectorsService_GetConnectorByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectorPluginSchema provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) GetConnectorPluginSchema(ctx context.Context, pluginID string, filter *domain.ConnectorPluginSchemaFilter) (domain.ConnectorPluginSchema, error) {
	ret := _mock.Called(ctx, pluginID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectorPluginSchema")
	}

	var r0 domain.ConnectorPluginSchema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.ConnectorPluginSchemaFilter) (domain.ConnectorPluginSchema, error)); ok {
		return returnFunc(ctx, pluginID, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.ConnectorPluginSchemaFilter) domain.ConnectorPluginSchema); ok {
		r0 = returnFunc(ctx, pluginID, filter)
	} else {
		r0 = ret.Get(0).(domain.ConnectorPluginSchema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *domain.ConnectorPluginSchemaFilter) error); ok {
		r1 = returnFunc(ctx, pluginID, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_GetConnectorPluginSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectorPluginSchema'
type MockConnectorsService_GetConnectorPluginSchema_Call struct {
	*mock.Call
}

// GetConnectorPluginSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - pluginID string
//   - filter *domain.ConnectorPluginSchemaFilter
func (_e *MockConnectorsService_Expecter) GetConnectorPluginSchema(ctx any, pluginID any, filter any) *MockConnectorsService_GetConnectorPluginSchema_Call {
	return &MockConnectorsService_GetConnectorPluginSchema_Call{Call: _e.mock.On("GetConnectorPluginSchema", ctx, pluginID, filter)}
}

func (_c *MockConnectorsService_GetConnectorPluginSchema_Call) Run(run func(ctx context.Context, pluginID string, filter *domain.ConnectorPluginSchemaFilter)) *MockConnectorsService_GetConnectorPluginSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *domain.ConnectorPluginSchemaFilter
		if args[2] != nil {
			arg2 = args[2].(*domain.ConnectorPluginSchemaFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectorsService_GetConnectorPluginSchema_Call) Return(connectorPluginSchema domain.ConnectorPluginSchema, err error) *MockConnectorsService_GetConnectorPluginSchema_Call {
	_c.Call.Return(connectorPluginSchema, err)
	return _c
}

func (_c *MockConnectorsService_GetConnectorPluginSchema_Call) RunAndReturn(run func(ctx context.Context, pluginID string, filter *domain.ConnectorPluginSchemaFilter) (domain.ConnectorPluginSchema, error)) *MockConnectorsService_GetConnectorPluginSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectorPlugins provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) GetConnectorPlugins(ctx context.Context) ([]domain.ConnectorPlugin, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectorPlugins")
	}

	var r0 []domain.ConnectorPlugin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.ConnectorPlugin, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.ConnectorPlugin); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ConnectorPlugin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_GetConnectorPlugins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectorPlugins'
type MockConnectorsService_GetConnectorPlugins_Call struct {
	*mock.Call
}

// GetConnectorPlugins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnectorsService_Expecter) GetConnectorPlugins(ctx any) *MockConnectorsService_GetConnectorPlugins_Call {
	return &MockConnectorsService_GetConnectorPlugins_Call{Call: _e.mock.On("GetConnectorPlugins", ctx)}
}

func (_c *MockConnectorsService_GetConnectorPlugins_Call) Run(run func(ctx context.Context)) *MockConnectorsService_GetConnectorPlugins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectorsService_GetConnectorPlugins_Call) Return(connectorPlugins []domain.ConnectorPlugin, err error) *MockConnectorsService_GetConnectorPlugins_Call {
	_c.Call.Return(connectorPlugins, err)
	return _c
}

func (_c *MockConnectorsService_GetConnectorPlugins_Call) RunAndReturn(run func(ctx context.Context) ([]domain.ConnectorPlugin, error)) *MockConnectorsService_GetConnectorPlugins_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectors provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) GetConnectors(ctx context.Context, filter *domain.ConnectorFilter) ([]domain.Connector, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectors")
	}

	var r0 []domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ConnectorFilter) ([]domain.Connector, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ConnectorFilter) []domain.Connector); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Connector)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.ConnectorFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_GetConnectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectors'
type MockConnectorsService_GetConnectors_Call struct {
	*mock.Call
}

// GetConnectors is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *domain.ConnectorFilter
func (_e *MockConnectorsService_Expecter) GetConnectors(ctx any, filter any) *MockConnectorsService_GetConnectors_Call {
	return &MockConnectorsService_GetConnectors_Call{Call: _e.mock.On("GetConnectors", ctx, filter)}
}

func (_c *MockConnectorsService_GetConnectors_Call) Run(run func(ctx context.Context, filter *domain.ConnectorFilter)) *MockConnectorsService_GetConnectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ConnectorFilter
		if args[1] != nil {
			arg1 = args[1].(*domain.ConnectorFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectorsService_GetConnectors_Call) Return(connectors []domain.Connector, err error) *MockConnectorsService_GetConnectors_Call {
	_c.Call.Return(connectors, err)
	return _c
}

func (_c *MockConnectorsService_GetConnectors_Call) RunAndReturn(run func(ctx context.Context, filter *domain.ConnectorFilter) ([]domain.Connector, error)) *MockConnectorsService_GetConnectors_Call {
	_c.Call.Return(run)
	return _c
}

// GetSMTPluginSchema provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) GetSMTPluginSchema(ctx context.Context, pluginID string, filter *domain.ConnectorPluginSchemaFilter) (domain.ConnectorPluginSchema, error) {
	ret := _mock.Called(ctx, pluginID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetSMTPluginSchema")
	}

	var r0 domain.ConnectorPluginSchema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.ConnectorPluginSchemaFilter) (domain.ConnectorPluginSchema, error)); ok {
		return returnFunc(ctx, pluginID, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.ConnectorPluginSchemaFilter) domain.ConnectorPluginSchema); ok {
		r0 = returnFunc(ctx, pluginID, filter)
	} else {
		r0 = ret.Get(0).(domain.ConnectorPluginSchema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *domain.ConnectorPluginSchemaFilter) error); ok {
		r1 = returnFunc(ctx, pluginID, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_GetSMTPluginSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSMTPluginSchema'
type MockConnectorsService_GetSMTPluginSchema_Call struct {
	*mock.Call
}

// GetSMTPluginSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - pluginID string
//   - filter *domain.ConnectorPluginSchemaFilter
func (_e *MockConnectorsService_Expecter) GetSMTPluginSchema(ctx any, pluginID any, filter any) *MockConnectorsService_GetSMTPluginSchema_Call {
	return &MockConnectorsService_GetSMTPluginSchema_Call{Call: _e.mock.On("GetSMTPluginSchema", ctx, pluginID, filter)}
}

func (_c *MockConnectorsService_GetSMTPluginSchema_Call) Run(run func(ctx context.Context, pluginID string, filter *domain.ConnectorPluginSchemaFilter)) *MockConnectorsService_GetSMTPluginSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *domain.ConnectorPluginSchemaFilter
		if args[2] != nil {
			arg2 = args[2].(*domain.ConnectorPluginSchemaFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectorsService_GetSMTPluginSchema_Call) Return(connectorPluginSchema domain.ConnectorPluginSchema, err error) *MockConnectorsService_GetSMTPluginSchema_Call {
	_c.Call.Return(connectorPluginSchema, err)
	return _c
}

func (_c *MockConnectorsService_GetSMTPluginSchema_Call) RunAndReturn(run func(ctx context.Context, pluginID string, filter *domain.ConnectorPluginSchemaFilter) (domain.ConnectorPluginSchema, error)) *MockConnectorsService_GetSMTPluginSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetSMTPlugins provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) GetSMTPlugins(ctx context.Context) ([]domain.ConnectorPlugin, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSMTPlugins")
	}

	var r0 []domain.ConnectorPlugin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.ConnectorPlugin, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.ConnectorPlugin); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ConnectorPlugin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_GetSMTPlugins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSMTPlugins'
type MockConnectorsService_GetSMTPlugins_Call struct {
	*mock.Call
}

// GetSMTPlugins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnectorsService_Expecter) GetSMTPlugins(ctx any) *MockConnectorsService_GetSMTPlugins_Call {
	return &MockConnectorsService_GetSMTPlugins_Call{Call: _e.mock.On("GetSMTPlugins", ctx)}
}

func (_c *MockConnectorsService_GetSMTPlugins_Call) Run(run func(ctx context.Context)) *MockConnectorsService_GetSMTPlugins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectorsService_GetSMTPlugins_Call) Return(connectorPlugins []domain.ConnectorPlugin, err error) *MockConnectorsService_GetSMTPlugins_Call {
	_c.Call.Return(connectorPlugins, err)
	return _c
}

func (_c *MockConnectorsService_GetSMTPlugins_Call) RunAndReturn(run func(ctx context.Context) ([]domain.ConnectorPlugin, error)) *MockConnectorsService_GetSMTPlugins_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByID provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) GetTaskByID(ctx context.Context, name string, taskID int) (domain.Task, error) {
	ret := _mock.Called(ctx, name, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (domain.Task, error)); ok {
		return returnFunc(ctx, name, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) domain.Task); ok {
		r0 = returnFunc(ctx, name, taskID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, name, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_GetTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByID'
type MockConnectorsService_GetTaskByID_Call struct {
	*mock.Call
}

// GetTaskByID is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - taskID int
func (_e *MockConnectorsService_Expecter) GetTaskByID(ctx any, name any, taskID any) *MockConnectorsService_GetTaskByID_Call {
	return &MockConnectorsService_GetTaskByID_Call{Call: _e.mock.On("GetTaskByID", ctx, name, taskID)}
}

func (_c *MockConnectorsService_GetTaskByID_Call) Run(run func(ctx context.Context, name string, taskID int)) *MockConnectorsService_GetTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectorsService_GetTaskByID_Call) Return(task domain.Task, err error) *MockConnectorsService_GetTaskByID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockConnectorsService_GetTaskByID_Call) RunAndReturn(run func(ctx context.Context, name string, taskID int) (domain.Task, error)) *MockConnectorsService_GetTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// PauseConnector provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) PauseConnector(ctx context.Context, name string) (domain.Connector, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for PauseConnector")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Connector, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Connector); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_PauseConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseConnector'
type MockConnectorsService_PauseConnector_Call struct {
	*mock.Call
}

// PauseConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockConnectorsService_Expecter) PauseConnector(ctx any, name any) *MockConnectorsService_PauseConnector_Call {
	return &MockConnectorsService_PauseConnector_Call{Call: _e.mock.On("PauseConnector", ctx, name)}
}

func (_c *MockConnectorsService_PauseConnector_Call) Run(run func(ctx context.Context, name string)) *MockConnectorsService_PauseConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectorsService_PauseConnector_Call) Return(connector domain.Connector, err error) *MockConnectorsService_PauseConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockConnectorsService_PauseConnector_Call) RunAndReturn(run func(ctx context.Context, name string) (domain.Connector, error)) *MockConnectorsService_PauseConnector_Call {
	_c.Call.Return(run)
	return _c
}

// RestartConnector provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) RestartConnector(ctx context.Context, name string, includeTasks bool, onlyFailed bool) (domain.Connector, error) {
	ret := _mock.Called(ctx, name, includeTasks, onlyFailed)

	if len(ret) == 0 {
		panic("no return value specified for RestartConnector")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool) (domain.Connector, error)); ok {
		return returnFunc(ctx, name, includeTasks, onlyFailed)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool) domain.Connector); ok {
		r0 = returnFunc(ctx, name, includeTasks, onlyFailed)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool, bool) error); ok {
		r1 = returnFunc(ctx, name, includeTasks, onlyFailed)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_RestartConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartConnector'
type MockConnectorsService_RestartConnector_Call struct {
	*mock.Call
}

// RestartConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - includeTasks bool
//   - onlyFailed bool
func (_e *MockConnectorsService_Expecter) RestartConnector(ctx any, name any, includeTasks any, onlyFailed any) *MockConnectorsService_RestartConnector_Call {
	return &MockConnectorsService_RestartConnector_Call{Call: _e.mock.On("RestartConnector", ctx, name, includeTasks, onlyFailed)}
}

func (_c *MockConnectorsService_RestartConnector_Call) Run(run func(ctx context.Context, name string, includeTasks bool, onlyFailed bool)) *MockConnectorsService_RestartConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConnectorsService_RestartConnector_Call) Return(connector domain.Connector, err error) *MockConnectorsService_RestartConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockConnectorsService_RestartConnector_Call) RunAndReturn(run func(ctx context.Context, name string, includeTasks bool, onlyFailed bool) (domain.Connector, error)) *MockConnectorsService_RestartConnector_Call {
	_c.Call.Return(run)
	return _c
}

// RestartTask provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) RestartTask(ctx context.Context, name string, taskID int) error {
	ret := _mock.Called(ctx, name, taskID)

	if len(ret) == 0 {
		panic("no return value specified for RestartTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, name, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectorsService_RestartTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartTask'
type MockConnectorsService_RestartTask_Call struct {
	*mock.Call
}

// RestartTask is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - taskID int
func (_e *MockConnectorsService_Expecter) RestartTask(ctx any, name any, taskID any) *MockConnectorsService_RestartTask_Call {
	return &MockConnectorsService_RestartTask_Call{Call: _e.mock.On("RestartTask", ctx, name, taskID)}
}

func (_c *MockConnectorsService_RestartTask_Call) Run(run func(ctx context.Context, name string, taskID int)) *MockConnectorsService_RestartTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectorsService_RestartTask_Call) Return(err error) *MockConnectorsService_RestartTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectorsService_RestartTask_Call) RunAndReturn(run func(ctx context.Context, name string, taskID int) error) *MockConnectorsService_RestartTask_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeConnector provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) ResumeConnector(ctx context.Context, name string) (domain.Connector, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ResumeConnector")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Connector, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Connector); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_ResumeConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeConnector'
type MockConnectorsService_ResumeConnector_Call struct {
	*mock.Call
}

// ResumeConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockConnectorsService_Expecter) ResumeConnector(ctx any, name any) *MockConnectorsService_ResumeConnector_Call {
	return &MockConnectorsService_ResumeConnector_Call{Call: _e.mock.On("ResumeConnector", ctx, name)}
}

func (_c *MockConnectorsService_ResumeConnector_Call) Run(run func(ctx context.Context, name string)) *MockConnectorsService_ResumeConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectorsService_ResumeConnector_Call) Return(connector domain.Connector, err error) *MockConnectorsService_ResumeConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockConnectorsService_ResumeConnector_Call) RunAndReturn(run func(ctx context.Context, name string) (domain.Connector, error)) *MockConnectorsService_ResumeConnector_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConnector provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) UpdateConnector(ctx context.Context, name string, config map[string]string) (domain.Connector, error) {
	ret := _mock.Called(ctx, name, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnector")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) (domain.Connector, error)); ok {
		return returnFunc(ctx, name, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) domain.Connector); ok {
		r0 = returnFunc(ctx, name, config)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = returnFunc(ctx, name, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_UpdateConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConnector'
type MockConnectorsService_UpdateConnector_Call struct {
	*mock.Call
}

// UpdateConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - config map[string]string
func (_e *MockConnectorsService_Expecter) UpdateConnector(ctx any, name any, config any) *MockConnectorsService_UpdateConnector_Call {
	return &MockConnectorsService_UpdateConnector_Call{Call: _e.mock.On("UpdateConnector", ctx, name, config)}
}

func (_c *MockConnectorsService_UpdateConnector_Call) Run(run func(ctx context.Context, name string, config map[string]string)) *MockConnectorsService_UpdateConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectorsService_UpdateConnector_Call) Return(connector domain.Connector, err error) *MockConnectorsService_UpdateConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockConnectorsService_UpdateConnector_Call) RunAndReturn(run func(ctx context.Context, name string, config map[string]string) (domain.Connector, error)) *MockConnectorsService_UpdateConnector_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateConnector provides a mock function for the type MockConnectorsService
func (_mock *MockConnectorsService) ValidateConnector(ctx context.Context, pluginType string, config map[string]string) (domain.ValidationReport, error) {
	ret := _mock.Called(ctx, pluginType, config)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConnector")
	}

	var r0 domain.ValidationReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) (domain.ValidationReport, error)); ok {
		return returnFunc(ctx, pluginType, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) domain.ValidationReport); ok {
		r0 = returnFunc(ctx, pluginType, config)
	} else {
		r0 = ret.Get(0).(domain.ValidationReport)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = returnFunc(ctx, pluginType, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectorsService_ValidateConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConnector'
type MockConnectorsService_ValidateConnector_Call struct {
	*mock.Call
}

// ValidateConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - pluginType string
//   - config map[string]string
func (_e *MockConnectorsService_Expecter) ValidateConnector(ctx any, pluginType any, config any) *MockConnectorsService_ValidateConnector_Call {
	return &MockConnectorsService_ValidateConnector_Call{Call: _e.mock.On("ValidateConnector", ctx, pluginType, config)}
}

func (_c *MockConnectorsService_ValidateConnector_Call) Run(run func(ctx context.Context, pluginType string, config map[string]string)) *MockConnectorsService_ValidateConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectorsService_ValidateConnector_Call) Return(validationReport domain.ValidationReport, err error) *MockConnectorsService_ValidateConnector_Call {
	_c.Call.Return(validationReport, err)
	return _c
}

func (_c *MockConnectorsService_ValidateConnector_Call) RunAndReturn(run func(ctx context.Context, pluginType string, config map[string]string) (domain.ValidationReport, error)) *MockConnectorsService_ValidateConnector_Call {
	_c.Call.Return(run)
	return _c
}
