// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"context"

	"github.com/daniildddd/maestro/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordHasher creates a new instance of MockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordHasher {
	mock := &MockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type MockPasswordHasher struct {
	mock.Mock
}

type MockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordHasher) EXPECT() *MockPasswordHasher_Expecter {
	return &MockPasswordHasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockPasswordHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password
func (_e *MockPasswordHasher_Expecter) Hash(password interface{}) *MockPasswordHasher_Hash_Call {
	return &MockPasswordHasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockPasswordHasher_Hash_Call) Run(run func(password string)) *MockPasswordHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPasswordHasher_Hash_Call) Return(s string, err error) *MockPasswordHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordHasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *MockPasswordHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) Verify(hash string, plain string) error {
	ret := _mock.Called(hash, plain)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hash, plain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordHasher_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPasswordHasher_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - hash
//   - plain
func (_e *MockPasswordHasher_Expecter) Verify(hash interface{}, plain interface{}) *MockPasswordHasher_Verify_Call {
	return &MockPasswordHasher_Verify_Call{Call: _e.mock.On("Verify", hash, plain)}
}

func (_c *MockPasswordHasher_Verify_Call) Run(run func(hash string, plain string)) *MockPasswordHasher_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordHasher_Verify_Call) Return(err error) *MockPasswordHasher_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordHasher_Verify_Call) RunAndReturn(run func(hash string, plain string) error) *MockPasswordHasher_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) CreateUser(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUsersRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockUsersRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUsersRepository_CreateUser_Call {
	return &MockUsersRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUsersRepository_CreateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockUsersRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) Return(user1 domain.User, err error) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (domain.User, error)) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUsersRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUsersRepository_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUsersRepository_DeleteUser_Call {
	return &MockUsersRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUsersRepository_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsersRepository_DeleteUser_Call) Return(err error) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByID(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUsersRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUsersRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUsersRepository_GetUserByID_Call {
	return &MockUsersRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUsersRepository_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByID_Call) Return(user domain.User, err error) *MockUsersRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockUsersRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUsers(ctx context.Context, filter domain.UserFilter) ([]domain.User, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserFilter) ([]domain.User, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserFilter) []domain.User); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUsersRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx
//   - filter
func (_e *MockUsersRepository_Expecter) GetUsers(ctx interface{}, filter interface{}) *MockUsersRepository_GetUsers_Call {
	return &MockUsersRepository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, filter)}
}

func (_c *MockUsersRepository_GetUsers_Call) Run(run func(ctx context.Context, filter domain.UserFilter)) *MockUsersRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserFilter))
	})
	return _c
}

func (_c *MockUsersRepository_GetUsers_Call) Return(users []domain.User, err error) *MockUsersRepository_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUsersRepository_GetUsers_Call) RunAndReturn(run func(ctx context.Context, filter domain.UserFilter) ([]domain.User, error)) *MockUsersRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}
