// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cleanup_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExpiredTokenCleaner creates a new instance of MockExpiredTokenCleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpiredTokenCleaner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpiredTokenCleaner {
	mock := &MockExpiredTokenCleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExpiredTokenCleaner is an autogenerated mock type for the ExpiredTokenCleaner type
type MockExpiredTokenCleaner struct {
	mock.Mock
}

type MockExpiredTokenCleaner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpiredTokenCleaner) EXPECT() *MockExpiredTokenCleaner_Expecter {
	return &MockExpiredTokenCleaner_Expecter{mock: &_m.Mock}
}

// DeleteExpiredRefreshTokens provides a mock function for the type MockExpiredTokenCleaner
func (_mock *MockExpiredTokenCleaner) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredRefreshTokens")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExpiredTokenCleaner_DeleteExpiredRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredRefreshTokens'
type MockExpiredTokenCleaner_DeleteExpiredRefreshTokens_Call struct {
	*mock.Call
}

// DeleteExpiredRefreshTokens is a helper method to define mock.On call
//   - ctx
func (_e *MockExpiredTokenCleaner_Expecter) DeleteExpiredRefreshTokens(ctx interface{}) *MockExpiredTokenCleaner_DeleteExpiredRefreshTokens_Call {
	return &MockExpiredTokenCleaner_DeleteExpiredRefreshTokens_Call{Call: _e.mock.On("DeleteExpiredRefreshTokens", ctx)}
}

func (_c *MockExpiredTokenCleaner_DeleteExpiredRefreshTokens_Call) Run(run func(ctx context.Context)) *MockExpiredTokenCleaner_DeleteExpiredRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockExpiredTokenCleaner_DeleteExpiredRefreshTokens_Call) Return(n int64, err error) *MockExpiredTokenCleaner_DeleteExpiredRefreshTokens_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockExpiredTokenCleaner_DeleteExpiredRefreshTokens_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockExpiredTokenCleaner_DeleteExpiredRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}
