// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transport_test

import (
	"context"

	"github.com/daniildddd/maestro/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsersService creates a new instance of MockUsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersService {
	mock := &MockUsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersService is an autogenerated mock type for the UsersService type
type MockUsersService struct {
	mock.Mock
}

type MockUsersService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersService) EXPECT() *MockUsersService_Expecter {
	return &MockUsersService_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function for the type MockUsersService
func (_mock *MockUsersService) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUsersService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUsersService_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUsersService_DeleteUser_Call {
	return &MockUsersService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUsersService_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsersService_DeleteUser_Call) Return(err error) *MockUsersService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockUsersService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUsersService
func (_mock *MockUsersService) GetUserByID(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUsersService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUsersService_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUsersService_GetUserByID_Call {
	return &MockUsersService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUsersService_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsersService_GetUserByID_Call) Return(user domain.User, err error) *MockUsersService_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersService_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockUsersService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockUsersService
func (_mock *MockUsersService) GetUsers(ctx context.Context, filter domain.UserFilter) ([]domain.User, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserFilter) ([]domain.User, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserFilter) []domain.User); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersService_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUsersService_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx
//   - filter
func (_e *MockUsersService_Expecter) GetUsers(ctx interface{}, filter interface{}) *MockUsersService_GetUsers_Call {
	return &MockUsersService_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, filter)}
}

func (_c *MockUsersService_GetUsers_Call) Run(run func(ctx context.Context, filter domain.UserFilter)) *MockUsersService_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserFilter))
	})
	return _c
}

func (_c *MockUsersService_GetUsers_Call) Return(users []domain.User, err error) *MockUsersService_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUsersService_GetUsers_Call) RunAndReturn(run func(ctx context.Context, filter domain.UserFilter) ([]domain.User, error)) *MockUsersService_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}
