// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository_test

import (
	"context"
	"time"

	"github.com/daniildddd/maestro/internal/core/repository/postgres"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPool creates a new instance of MockPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPool {
	mock := &MockPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPool is an autogenerated mock type for the Pool type
type MockPool struct {
	mock.Mock
}

type MockPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPool) EXPECT() *MockPool_Expecter {
	return &MockPool_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockPool
func (_mock *MockPool) Close() {
	_mock.Called()
	return
}

// MockPool_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPool_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPool_Expecter) Close() *MockPool_Close_Call {
	return &MockPool_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPool_Close_Call) Run(run func()) *MockPool_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_Close_Call) Return() *MockPool_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPool_Close_Call) RunAndReturn(run func()) *MockPool_Close_Call {
	_c.Run(run)
	return _c
}

// Exec provides a mock function for the type MockPool
func (_mock *MockPool) Exec(ctx context.Context, sql string, args ...any) (postgres.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 postgres.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []any) (postgres.CommandTag, error)); ok {
		return returnFunc(ctx, sql, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) postgres.CommandTag); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(postgres.CommandTag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPool_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockPool_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx
//   - sql
//   - args
func (_e *MockPool_Expecter) Exec(ctx interface{}, sql interface{}, args ...interface{}) *MockPool_Exec_Call {
	return &MockPool_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockPool_Exec_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockPool_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockPool_Exec_Call) Return(commandTag postgres.CommandTag, err error) *MockPool_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockPool_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (postgres.CommandTag, error)) *MockPool_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// OpTimeout provides a mock function for the type MockPool
func (_mock *MockPool) OpTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockPool_OpTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpTimeout'
type MockPool_OpTimeout_Call struct {
	*mock.Call
}

// OpTimeout is a helper method to define mock.On call
func (_e *MockPool_Expecter) OpTimeout() *MockPool_OpTimeout_Call {
	return &MockPool_OpTimeout_Call{Call: _e.mock.On("OpTimeout")}
}

func (_c *MockPool_OpTimeout_Call) Run(run func()) *MockPool_OpTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_OpTimeout_Call) Return(duration time.Duration) *MockPool_OpTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockPool_OpTimeout_Call) RunAndReturn(run func() time.Duration) *MockPool_OpTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockPool
func (_mock *MockPool) Query(ctx context.Context, sql string, args ...any) (postgres.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 postgres.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []any) (postgres.Rows, error)); ok {
		return returnFunc(ctx, sql, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) postgres.Rows); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(postgres.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPool_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockPool_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx
//   - sql
//   - args
func (_e *MockPool_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *MockPool_Query_Call {
	return &MockPool_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockPool_Query_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockPool_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockPool_Query_Call) Return(rows postgres.Rows, err error) *MockPool_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockPool_Query_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (postgres.Rows, error)) *MockPool_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockPool
func (_mock *MockPool) QueryRow(ctx context.Context, sql string, args ...any) postgres.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 postgres.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) postgres.Row); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(postgres.Row)
		}
	}
	return r0
}

// MockPool_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockPool_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx
//   - sql
//   - args
func (_e *MockPool_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *MockPool_QueryRow_Call {
	return &MockPool_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockPool_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockPool_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockPool_QueryRow_Call) Return(row postgres.Row) *MockPool_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockPool_QueryRow_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) postgres.Row) *MockPool_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRow creates a new instance of MockRow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRow {
	mock := &MockRow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRow is an autogenerated mock type for the Row type
type MockRow struct {
	mock.Mock
}

type MockRow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRow) EXPECT() *MockRow_Expecter {
	return &MockRow_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function for the type MockRow
func (_mock *MockRow) Scan(dest ...any) error {
	var tmpRet mock.Arguments
	if len(dest) > 0 {
		tmpRet = _mock.Called(dest)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...any) error); ok {
		r0 = returnFunc(dest...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRow_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockRow_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest
func (_e *MockRow_Expecter) Scan(dest ...interface{}) *MockRow_Scan_Call {
	return &MockRow_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *MockRow_Scan_Call) Run(run func(dest ...any)) *MockRow_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockRow_Scan_Call) Return(err error) *MockRow_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRow_Scan_Call) RunAndReturn(run func(dest ...any) error) *MockRow_Scan_Call {
	_c.Call.Return(run)
	return _c
}
