// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"context"

	"github.com/daniildddd/maestro/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserDirectory creates a new instance of MockUserDirectory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserDirectory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserDirectory {
	mock := &MockUserDirectory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserDirectory is an autogenerated mock type for the UserDirectory type
type MockUserDirectory struct {
	mock.Mock
}

type MockUserDirectory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserDirectory) EXPECT() *MockUserDirectory_Expecter {
	return &MockUserDirectory_Expecter{mock: &_m.Mock}
}

// GetUsersByIDs provides a mock function for the type MockUserDirectory
func (_mock *MockUserDirectory) GetUsersByIDs(ctx context.Context, ids []uuid.UUID) ([]domain.User, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByIDs")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]domain.User, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []domain.User); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDirectory_GetUsersByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByIDs'
type MockUserDirectory_GetUsersByIDs_Call struct {
	*mock.Call
}

// GetUsersByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockUserDirectory_Expecter) GetUsersByIDs(ctx any, ids any) *MockUserDirectory_GetUsersByIDs_Call {
	return &MockUserDirectory_GetUsersByIDs_Call{Call: _e.mock.On("GetUsersByIDs", ctx, ids)}
}

func (_c *MockUserDirectory_GetUsersByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockUserDirectory_GetUsersByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserDirectory_GetUsersByIDs_Call) Return(users []domain.User, err error) *MockUserDirectory_GetUsersByIDs_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserDirectory_GetUsersByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) ([]domain.User, error)) *MockUserDirectory_GetUsersByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditRepository creates a new instance of MockAuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditRepository {
	mock := &MockAuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditRepository is an autogenerated mock type for the AuditRepository type
type MockAuditRepository struct {
	mock.Mock
}

type MockAuditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditRepository) EXPECT() *MockAuditRepository_Expecter {
	return &MockAuditRepository_Expecter{mock: &_m.Mock}
}

// DeleteLogByID provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) DeleteLogByID(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLogByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditRepository_DeleteLogByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLogByID'
type MockAuditRepository_DeleteLogByID_Call struct {
	*mock.Call
}

// DeleteLogByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuditRepository_Expecter) DeleteLogByID(ctx any, id any) *MockAuditRepository_DeleteLogByID_Call {
	return &MockAuditRepository_DeleteLogByID_Call{Call: _e.mock.On("DeleteLogByID", ctx, id)}
}

func (_c *MockAuditRepository_DeleteLogByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuditRepository_DeleteLogByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_DeleteLogByID_Call) Return(err error) *MockAuditRepository_DeleteLogByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditRepository_DeleteLogByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAuditRepository_DeleteLogByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogByID provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) GetLogByID(ctx context.Context, id uuid.UUID) (domain.AuditEvent, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLogByID")
	}

	var r0 domain.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.AuditEvent, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.AuditEvent); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.AuditEvent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditRepository_GetLogByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogByID'
type MockAuditRepository_GetLogByID_Call struct {
	*mock.Call
}

// GetLogByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuditRepository_Expecter) GetLogByID(ctx any, id any) *MockAuditRepository_GetLogByID_Call {
	return &MockAuditRepository_GetLogByID_Call{Call: _e.mock.On("GetLogByID", ctx, id)}
}

func (_c *MockAuditRepository_GetLogByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuditRepository_GetLogByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_GetLogByID_Call) Return(auditEvent domain.AuditEvent, err error) *MockAuditRepository_GetLogByID_Call {
	_c.Call.Return(auditEvent, err)
	return _c
}

func (_c *MockAuditRepository_GetLogByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.AuditEvent, error)) *MockAuditRepository_GetLogByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogs provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) GetLogs(ctx context.Context, filter *domain.AuditLogFilter) ([]domain.AuditEvent, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []domain.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditLogFilter) ([]domain.AuditEvent, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditLogFilter) []domain.AuditEvent); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditLogFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditRepository_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type MockAuditRepository_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *domain.AuditLogFilter
func (_e *MockAuditRepository_Expecter) GetLogs(ctx any, filter any) *MockAuditRepository_GetLogs_Call {
	return &MockAuditRepository_GetLogs_Call{Call: _e.mock.On("GetLogs", ctx, filter)}
}

func (_c *MockAuditRepository_GetLogs_Call) Run(run func(ctx context.Context, filter *domain.AuditLogFilter)) *MockAuditRepository_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditLogFilter
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditLogFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_GetLogs_Call) Return(auditEvents []domain.AuditEvent, err error) *MockAuditRepository_GetLogs_Call {
	_c.Call.Return(auditEvents, err)
	return _c
}

func (_c *MockAuditRepository_GetLogs_Call) RunAndReturn(run func(ctx context.Context, filter *domain.AuditLogFilter) ([]domain.AuditEvent, error)) *MockAuditRepository_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}
