// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transport_test

import (
	"context"

	"github.com/daniildddd/maestro/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditService creates a new instance of MockAuditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditService {
	mock := &MockAuditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditService is an autogenerated mock type for the AuditService type
type MockAuditService struct {
	mock.Mock
}

type MockAuditService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditService) EXPECT() *MockAuditService_Expecter {
	return &MockAuditService_Expecter{mock: &_m.Mock}
}

// DeleteLogByID provides a mock function for the type MockAuditService
func (_mock *MockAuditService) DeleteLogByID(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLogByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditService_DeleteLogByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLogByID'
type MockAuditService_DeleteLogByID_Call struct {
	*mock.Call
}

// DeleteLogByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuditService_Expecter) DeleteLogByID(ctx any, id any) *MockAuditService_DeleteLogByID_Call {
	return &MockAuditService_DeleteLogByID_Call{Call: _e.mock.On("DeleteLogByID", ctx, id)}
}

func (_c *MockAuditService_DeleteLogByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuditService_DeleteLogByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditService_DeleteLogByID_Call) Return(err error) *MockAuditService_DeleteLogByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditService_DeleteLogByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAuditService_DeleteLogByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogByID provides a mock function for the type MockAuditService
func (_mock *MockAuditService) GetLogByID(ctx context.Context, id uuid.UUID) (domain.AuditEvent, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLogByID")
	}

	var r0 domain.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.AuditEvent, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.AuditEvent); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.AuditEvent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditService_GetLogByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogByID'
type MockAuditService_GetLogByID_Call struct {
	*mock.Call
}

// GetLogByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuditService_Expecter) GetLogByID(ctx any, id any) *MockAuditService_GetLogByID_Call {
	return &MockAuditService_GetLogByID_Call{Call: _e.mock.On("GetLogByID", ctx, id)}
}

func (_c *MockAuditService_GetLogByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuditService_GetLogByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditService_GetLogByID_Call) Return(auditEvent domain.AuditEvent, err error) *MockAuditService_GetLogByID_Call {
	_c.Call.Return(auditEvent, err)
	return _c
}

func (_c *MockAuditService_GetLogByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.AuditEvent, error)) *MockAuditService_GetLogByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogs provides a mock function for the type MockAuditService
func (_mock *MockAuditService) GetLogs(ctx context.Context, filter *domain.AuditLogFilter) ([]domain.AuditEvent, bool, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []domain.AuditEvent
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditLogFilter) ([]domain.AuditEvent, bool, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditLogFilter) []domain.AuditEvent); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditLogFilter) bool); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *domain.AuditLogFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuditService_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type MockAuditService_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *domain.AuditLogFilter
func (_e *MockAuditService_Expecter) GetLogs(ctx any, filter any) *MockAuditService_GetLogs_Call {
	return &MockAuditService_GetLogs_Call{Call: _e.mock.On("GetLogs", ctx, filter)}
}

func (_c *MockAuditService_GetLogs_Call) Run(run func(ctx context.Context, filter *domain.AuditLogFilter)) *MockAuditService_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditLogFilter
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditLogFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditService_GetLogs_Call) Return(auditEvents []domain.AuditEvent, b bool, err error) *MockAuditService_GetLogs_Call {
	_c.Call.Return(auditEvents, b, err)
	return _c
}

func (_c *MockAuditService_GetLogs_Call) RunAndReturn(run func(ctx context.Context, filter *domain.AuditLogFilter) ([]domain.AuditEvent, bool, error)) *MockAuditService_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}
