// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"context"

	"github.com/daniildddd/maestro/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockdbChecker creates a new instance of MockdbChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdbChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdbChecker {
	mock := &MockdbChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockdbChecker is an autogenerated mock type for the dbChecker type
type MockdbChecker struct {
	mock.Mock
}

type MockdbChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdbChecker) EXPECT() *MockdbChecker_Expecter {
	return &MockdbChecker_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockdbChecker
func (_mock *MockdbChecker) Check(ctx context.Context, config map[string]string) ([]domain.ValidationStep, error) {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 []domain.ValidationStep
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) ([]domain.ValidationStep, error)); ok {
		return returnFunc(ctx, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) []domain.ValidationStep); ok {
		r0 = returnFunc(ctx, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ValidationStep)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = returnFunc(ctx, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockdbChecker_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockdbChecker_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - config map[string]string
func (_e *MockdbChecker_Expecter) Check(ctx any, config any) *MockdbChecker_Check_Call {
	return &MockdbChecker_Check_Call{Call: _e.mock.On("Check", ctx, config)}
}

func (_c *MockdbChecker_Check_Call) Run(run func(ctx context.Context, config map[string]string)) *MockdbChecker_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockdbChecker_Check_Call) Return(validationSteps []domain.ValidationStep, err error) *MockdbChecker_Check_Call {
	_c.Call.Return(validationSteps, err)
	return _c
}

func (_c *MockdbChecker_Check_Call) RunAndReturn(run func(ctx context.Context, config map[string]string) ([]domain.ValidationStep, error)) *MockdbChecker_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Match provides a mock function for the type MockdbChecker
func (_mock *MockdbChecker) Match(class string) bool {
	ret := _mock.Called(class)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(class)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockdbChecker_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockdbChecker_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - class string
func (_e *MockdbChecker_Expecter) Match(class any) *MockdbChecker_Match_Call {
	return &MockdbChecker_Match_Call{Call: _e.mock.On("Match", class)}
}

func (_c *MockdbChecker_Match_Call) Run(run func(class string)) *MockdbChecker_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockdbChecker_Match_Call) Return(b bool) *MockdbChecker_Match_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockdbChecker_Match_Call) RunAndReturn(run func(class string) bool) *MockdbChecker_Match_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKafkaConnect creates a new instance of MockKafkaConnect. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaConnect(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaConnect {
	mock := &MockKafkaConnect{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKafkaConnect is an autogenerated mock type for the KafkaConnect type
type MockKafkaConnect struct {
	mock.Mock
}

type MockKafkaConnect_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKafkaConnect) EXPECT() *MockKafkaConnect_Expecter {
	return &MockKafkaConnect_Expecter{mock: &_m.Mock}
}

// CreateConnector provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) CreateConnector(ctx context.Context, name string, config map[string]string) (domain.Connector, error) {
	ret := _mock.Called(ctx, name, config)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnector")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) (domain.Connector, error)); ok {
		return returnFunc(ctx, name, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) domain.Connector); ok {
		r0 = returnFunc(ctx, name, config)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = returnFunc(ctx, name, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_CreateConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConnector'
type MockKafkaConnect_CreateConnector_Call struct {
	*mock.Call
}

// CreateConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - config map[string]string
func (_e *MockKafkaConnect_Expecter) CreateConnector(ctx any, name any, config any) *MockKafkaConnect_CreateConnector_Call {
	return &MockKafkaConnect_CreateConnector_Call{Call: _e.mock.On("CreateConnector", ctx, name, config)}
}

func (_c *MockKafkaConnect_CreateConnector_Call) Run(run func(ctx context.Context, name string, config map[string]string)) *MockKafkaConnect_CreateConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_CreateConnector_Call) Return(connector domain.Connector, err error) *MockKafkaConnect_CreateConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockKafkaConnect_CreateConnector_Call) RunAndReturn(run func(ctx context.Context, name string, config map[string]string) (domain.Connector, error)) *MockKafkaConnect_CreateConnector_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKafkaConnect_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKafkaConnect_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockKafkaConnect_Expecter) Delete(ctx any, name any) *MockKafkaConnect_Delete_Call {
	return &MockKafkaConnect_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockKafkaConnect_Delete_Call) Run(run func(ctx context.Context, name string)) *MockKafkaConnect_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_Delete_Call) Return(err error) *MockKafkaConnect_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKafkaConnect_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockKafkaConnect_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectorByID provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) GetConnectorByID(ctx context.Context, name string) (domain.Connector, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectorByID")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Connector, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Connector); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_GetConnectorByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectorByID'
type MockKafkaConnect_GetConnectorByID_Call struct {
	*mock.Call
}

// GetConnectorByID is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockKafkaConnect_Expecter) GetConnectorByID(ctx any, name any) *MockKafkaConnect_GetConnectorByID_Call {
	return &MockKafkaConnect_GetConnectorByID_Call{Call: _e.mock.On("GetConnectorByID", ctx, name)}
}

func (_c *MockKafkaConnect_GetConnectorByID_Call) Run(run func(ctx context.Context, name string)) *MockKafkaConnect_GetConnectorByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_GetConnectorByID_Call) Return(connector domain.Connector, err error) *MockKafkaConnect_GetConnectorByID_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockKafkaConnect_GetConnectorByID_Call) RunAndReturn(run func(ctx context.Context, name string) (domain.Connector, error)) *MockKafkaConnect_GetConnectorByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectorPluginSchema provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) GetConnectorPluginSchema(ctx context.Context, pluginID string) (domain.ConnectorPluginSchema, error) {
	ret := _mock.Called(ctx, pluginID)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectorPluginSchema")
	}

	var r0 domain.ConnectorPluginSchema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.ConnectorPluginSchema, error)); ok {
		return returnFunc(ctx, pluginID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.ConnectorPluginSchema); ok {
		r0 = returnFunc(ctx, pluginID)
	} else {
		r0 = ret.Get(0).(domain.ConnectorPluginSchema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pluginID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_GetConnectorPluginSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectorPluginSchema'
type MockKafkaConnect_GetConnectorPluginSchema_Call struct {
	*mock.Call
}

// GetConnectorPluginSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - pluginID string
func (_e *MockKafkaConnect_Expecter) GetConnectorPluginSchema(ctx any, pluginID any) *MockKafkaConnect_GetConnectorPluginSchema_Call {
	return &MockKafkaConnect_GetConnectorPluginSchema_Call{Call: _e.mock.On("GetConnectorPluginSchema", ctx, pluginID)}
}

func (_c *MockKafkaConnect_GetConnectorPluginSchema_Call) Run(run func(ctx context.Context, pluginID string)) *MockKafkaConnect_GetConnectorPluginSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_GetConnectorPluginSchema_Call) Return(connectorPluginSchema domain.ConnectorPluginSchema, err error) *MockKafkaConnect_GetConnectorPluginSchema_Call {
	_c.Call.Return(connectorPluginSchema, err)
	return _c
}

func (_c *MockKafkaConnect_GetConnectorPluginSchema_Call) RunAndReturn(run func(ctx context.Context, pluginID string) (domain.ConnectorPluginSchema, error)) *MockKafkaConnect_GetConnectorPluginSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectorPluginSchemaWithValues provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) GetConnectorPluginSchemaWithValues(ctx context.Context, pluginID string) (domain.ConnectorPluginSchema, error) {
	ret := _mock.Called(ctx, pluginID)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectorPluginSchemaWithValues")
	}

	var r0 domain.ConnectorPluginSchema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.ConnectorPluginSchema, error)); ok {
		return returnFunc(ctx, pluginID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.ConnectorPluginSchema); ok {
		r0 = returnFunc(ctx, pluginID)
	} else {
		r0 = ret.Get(0).(domain.ConnectorPluginSchema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pluginID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_GetConnectorPluginSchemaWithValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectorPluginSchemaWithValues'
type MockKafkaConnect_GetConnectorPluginSchemaWithValues_Call struct {
	*mock.Call
}

// GetConnectorPluginSchemaWithValues is a helper method to define mock.On call
//   - ctx context.Context
//   - pluginID string
func (_e *MockKafkaConnect_Expecter) GetConnectorPluginSchemaWithValues(ctx any, pluginID any) *MockKafkaConnect_GetConnectorPluginSchemaWithValues_Call {
	return &MockKafkaConnect_GetConnectorPluginSchemaWithValues_Call{Call: _e.mock.On("GetConnectorPluginSchemaWithValues", ctx, pluginID)}
}

func (_c *MockKafkaConnect_GetConnectorPluginSchemaWithValues_Call) Run(run func(ctx context.Context, pluginID string)) *MockKafkaConnect_GetConnectorPluginSchemaWithValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_GetConnectorPluginSchemaWithValues_Call) Return(connectorPluginSchema domain.ConnectorPluginSchema, err error) *MockKafkaConnect_GetConnectorPluginSchemaWithValues_Call {
	_c.Call.Return(connectorPluginSchema, err)
	return _c
}

func (_c *MockKafkaConnect_GetConnectorPluginSchemaWithValues_Call) RunAndReturn(run func(ctx context.Context, pluginID string) (domain.ConnectorPluginSchema, error)) *MockKafkaConnect_GetConnectorPluginSchemaWithValues_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectorPlugins provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) GetConnectorPlugins(ctx context.Context) ([]domain.ConnectorPlugin, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectorPlugins")
	}

	var r0 []domain.ConnectorPlugin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.ConnectorPlugin, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.ConnectorPlugin); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ConnectorPlugin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_GetConnectorPlugins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectorPlugins'
type MockKafkaConnect_GetConnectorPlugins_Call struct {
	*mock.Call
}

// GetConnectorPlugins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKafkaConnect_Expecter) GetConnectorPlugins(ctx any) *MockKafkaConnect_GetConnectorPlugins_Call {
	return &MockKafkaConnect_GetConnectorPlugins_Call{Call: _e.mock.On("GetConnectorPlugins", ctx)}
}

func (_c *MockKafkaConnect_GetConnectorPlugins_Call) Run(run func(ctx context.Context)) *MockKafkaConnect_GetConnectorPlugins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_GetConnectorPlugins_Call) Return(connectorPlugins []domain.ConnectorPlugin, err error) *MockKafkaConnect_GetConnectorPlugins_Call {
	_c.Call.Return(connectorPlugins, err)
	return _c
}

func (_c *MockKafkaConnect_GetConnectorPlugins_Call) RunAndReturn(run func(ctx context.Context) ([]domain.ConnectorPlugin, error)) *MockKafkaConnect_GetConnectorPlugins_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectors provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) GetConnectors(ctx context.Context) ([]domain.Connector, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectors")
	}

	var r0 []domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Connector, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Connector); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Connector)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_GetConnectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectors'
type MockKafkaConnect_GetConnectors_Call struct {
	*mock.Call
}

// GetConnectors is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKafkaConnect_Expecter) GetConnectors(ctx any) *MockKafkaConnect_GetConnectors_Call {
	return &MockKafkaConnect_GetConnectors_Call{Call: _e.mock.On("GetConnectors", ctx)}
}

func (_c *MockKafkaConnect_GetConnectors_Call) Run(run func(ctx context.Context)) *MockKafkaConnect_GetConnectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_GetConnectors_Call) Return(connectors []domain.Connector, err error) *MockKafkaConnect_GetConnectors_Call {
	_c.Call.Return(connectors, err)
	return _c
}

func (_c *MockKafkaConnect_GetConnectors_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Connector, error)) *MockKafkaConnect_GetConnectors_Call {
	_c.Call.Return(run)
	return _c
}

// GetSMTPlugins provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) GetSMTPlugins(ctx context.Context) ([]domain.ConnectorPlugin, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSMTPlugins")
	}

	var r0 []domain.ConnectorPlugin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.ConnectorPlugin, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.ConnectorPlugin); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ConnectorPlugin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_GetSMTPlugins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSMTPlugins'
type MockKafkaConnect_GetSMTPlugins_Call struct {
	*mock.Call
}

// GetSMTPlugins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKafkaConnect_Expecter) GetSMTPlugins(ctx any) *MockKafkaConnect_GetSMTPlugins_Call {
	return &MockKafkaConnect_GetSMTPlugins_Call{Call: _e.mock.On("GetSMTPlugins", ctx)}
}

func (_c *MockKafkaConnect_GetSMTPlugins_Call) Run(run func(ctx context.Context)) *MockKafkaConnect_GetSMTPlugins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_GetSMTPlugins_Call) Return(connectorPlugins []domain.ConnectorPlugin, err error) *MockKafkaConnect_GetSMTPlugins_Call {
	_c.Call.Return(connectorPlugins, err)
	return _c
}

func (_c *MockKafkaConnect_GetSMTPlugins_Call) RunAndReturn(run func(ctx context.Context) ([]domain.ConnectorPlugin, error)) *MockKafkaConnect_GetSMTPlugins_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByID provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) GetTaskByID(ctx context.Context, name string, taskID int) (domain.Task, error) {
	ret := _mock.Called(ctx, name, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (domain.Task, error)); ok {
		return returnFunc(ctx, name, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) domain.Task); ok {
		r0 = returnFunc(ctx, name, taskID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, name, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_GetTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByID'
type MockKafkaConnect_GetTaskByID_Call struct {
	*mock.Call
}

// GetTaskByID is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - taskID int
func (_e *MockKafkaConnect_Expecter) GetTaskByID(ctx any, name any, taskID any) *MockKafkaConnect_GetTaskByID_Call {
	return &MockKafkaConnect_GetTaskByID_Call{Call: _e.mock.On("GetTaskByID", ctx, name, taskID)}
}

func (_c *MockKafkaConnect_GetTaskByID_Call) Run(run func(ctx context.Context, name string, taskID int)) *MockKafkaConnect_GetTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_GetTaskByID_Call) Return(task domain.Task, err error) *MockKafkaConnect_GetTaskByID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockKafkaConnect_GetTaskByID_Call) RunAndReturn(run func(ctx context.Context, name string, taskID int) (domain.Task, error)) *MockKafkaConnect_GetTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// PauseConnector provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) PauseConnector(ctx context.Context, name string) (domain.Connector, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for PauseConnector")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Connector, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Connector); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_PauseConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseConnector'
type MockKafkaConnect_PauseConnector_Call struct {
	*mock.Call
}

// PauseConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockKafkaConnect_Expecter) PauseConnector(ctx any, name any) *MockKafkaConnect_PauseConnector_Call {
	return &MockKafkaConnect_PauseConnector_Call{Call: _e.mock.On("PauseConnector", ctx, name)}
}

func (_c *MockKafkaConnect_PauseConnector_Call) Run(run func(ctx context.Context, name string)) *MockKafkaConnect_PauseConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_PauseConnector_Call) Return(connector domain.Connector, err error) *MockKafkaConnect_PauseConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockKafkaConnect_PauseConnector_Call) RunAndReturn(run func(ctx context.Context, name string) (domain.Connector, error)) *MockKafkaConnect_PauseConnector_Call {
	_c.Call.Return(run)
	return _c
}

// RestartConnector provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) RestartConnector(ctx context.Context, name string, includeTasks bool, onlyFailed bool) (domain.Connector, error) {
	ret := _mock.Called(ctx, name, includeTasks, onlyFailed)

	if len(ret) == 0 {
		panic("no return value specified for RestartConnector")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool) (domain.Connector, error)); ok {
		return returnFunc(ctx, name, includeTasks, onlyFailed)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool) domain.Connector); ok {
		r0 = returnFunc(ctx, name, includeTasks, onlyFailed)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool, bool) error); ok {
		r1 = returnFunc(ctx, name, includeTasks, onlyFailed)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_RestartConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartConnector'
type MockKafkaConnect_RestartConnector_Call struct {
	*mock.Call
}

// RestartConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - includeTasks bool
//   - onlyFailed bool
func (_e *MockKafkaConnect_Expecter) RestartConnector(ctx any, name any, includeTasks any, onlyFailed any) *MockKafkaConnect_RestartConnector_Call {
	return &MockKafkaConnect_RestartConnector_Call{Call: _e.mock.On("RestartConnector", ctx, name, includeTasks, onlyFailed)}
}

func (_c *MockKafkaConnect_RestartConnector_Call) Run(run func(ctx context.Context, name string, includeTasks bool, onlyFailed bool)) *MockKafkaConnect_RestartConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_RestartConnector_Call) Return(connector domain.Connector, err error) *MockKafkaConnect_RestartConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockKafkaConnect_RestartConnector_Call) RunAndReturn(run func(ctx context.Context, name string, includeTasks bool, onlyFailed bool) (domain.Connector, error)) *MockKafkaConnect_RestartConnector_Call {
	_c.Call.Return(run)
	return _c
}

// RestartTask provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) RestartTask(ctx context.Context, name string, taskID int) error {
	ret := _mock.Called(ctx, name, taskID)

	if len(ret) == 0 {
		panic("no return value specified for RestartTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, name, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKafkaConnect_RestartTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartTask'
type MockKafkaConnect_RestartTask_Call struct {
	*mock.Call
}

// RestartTask is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - taskID int
func (_e *MockKafkaConnect_Expecter) RestartTask(ctx any, name any, taskID any) *MockKafkaConnect_RestartTask_Call {
	return &MockKafkaConnect_RestartTask_Call{Call: _e.mock.On("RestartTask", ctx, name, taskID)}
}

func (_c *MockKafkaConnect_RestartTask_Call) Run(run func(ctx context.Context, name string, taskID int)) *MockKafkaConnect_RestartTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_RestartTask_Call) Return(err error) *MockKafkaConnect_RestartTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKafkaConnect_RestartTask_Call) RunAndReturn(run func(ctx context.Context, name string, taskID int) error) *MockKafkaConnect_RestartTask_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeConnector provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) ResumeConnector(ctx context.Context, name string) (domain.Connector, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ResumeConnector")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Connector, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Connector); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_ResumeConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeConnector'
type MockKafkaConnect_ResumeConnector_Call struct {
	*mock.Call
}

// ResumeConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockKafkaConnect_Expecter) ResumeConnector(ctx any, name any) *MockKafkaConnect_ResumeConnector_Call {
	return &MockKafkaConnect_ResumeConnector_Call{Call: _e.mock.On("ResumeConnector", ctx, name)}
}

func (_c *MockKafkaConnect_ResumeConnector_Call) Run(run func(ctx context.Context, name string)) *MockKafkaConnect_ResumeConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_ResumeConnector_Call) Return(connector domain.Connector, err error) *MockKafkaConnect_ResumeConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockKafkaConnect_ResumeConnector_Call) RunAndReturn(run func(ctx context.Context, name string) (domain.Connector, error)) *MockKafkaConnect_ResumeConnector_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConnector provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) UpdateConnector(ctx context.Context, name string, config map[string]string) (domain.Connector, error) {
	ret := _mock.Called(ctx, name, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnector")
	}

	var r0 domain.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) (domain.Connector, error)); ok {
		return returnFunc(ctx, name, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) domain.Connector); ok {
		r0 = returnFunc(ctx, name, config)
	} else {
		r0 = ret.Get(0).(domain.Connector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = returnFunc(ctx, name, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_UpdateConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConnector'
type MockKafkaConnect_UpdateConnector_Call struct {
	*mock.Call
}

// UpdateConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - config map[string]string
func (_e *MockKafkaConnect_Expecter) UpdateConnector(ctx any, name any, config any) *MockKafkaConnect_UpdateConnector_Call {
	return &MockKafkaConnect_UpdateConnector_Call{Call: _e.mock.On("UpdateConnector", ctx, name, config)}
}

func (_c *MockKafkaConnect_UpdateConnector_Call) Run(run func(ctx context.Context, name string, config map[string]string)) *MockKafkaConnect_UpdateConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_UpdateConnector_Call) Return(connector domain.Connector, err error) *MockKafkaConnect_UpdateConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *MockKafkaConnect_UpdateConnector_Call) RunAndReturn(run func(ctx context.Context, name string, config map[string]string) (domain.Connector, error)) *MockKafkaConnect_UpdateConnector_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateConfig provides a mock function for the type MockKafkaConnect
func (_mock *MockKafkaConnect) ValidateConfig(ctx context.Context, pluginID string, config map[string]string) ([]domain.ValidationCheck, error) {
	ret := _mock.Called(ctx, pluginID, config)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConfig")
	}

	var r0 []domain.ValidationCheck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) ([]domain.ValidationCheck, error)); ok {
		return returnFunc(ctx, pluginID, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) []domain.ValidationCheck); ok {
		r0 = returnFunc(ctx, pluginID, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ValidationCheck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = returnFunc(ctx, pluginID, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaConnect_ValidateConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConfig'
type MockKafkaConnect_ValidateConfig_Call struct {
	*mock.Call
}

// ValidateConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - pluginID string
//   - config map[string]string
func (_e *MockKafkaConnect_Expecter) ValidateConfig(ctx any, pluginID any, config any) *MockKafkaConnect_ValidateConfig_Call {
	return &MockKafkaConnect_ValidateConfig_Call{Call: _e.mock.On("ValidateConfig", ctx, pluginID, config)}
}

func (_c *MockKafkaConnect_ValidateConfig_Call) Run(run func(ctx context.Context, pluginID string, config map[string]string)) *MockKafkaConnect_ValidateConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKafkaConnect_ValidateConfig_Call) Return(validationChecks []domain.ValidationCheck, err error) *MockKafkaConnect_ValidateConfig_Call {
	_c.Call.Return(validationChecks, err)
	return _c
}

func (_c *MockKafkaConnect_ValidateConfig_Call) RunAndReturn(run func(ctx context.Context, pluginID string, config map[string]string) ([]domain.ValidationCheck, error)) *MockKafkaConnect_ValidateConfig_Call {
	_c.Call.Return(run)
	return _c
}
